/**
 * settings.js — Configuração central do ml-scraper-v2
 */

const settings = {
  PORT:                parseInt(process.env.PORT                || '3001'),
  REDIS_URL:           process.env.REDIS_URL,
  AFILIADO_TAG:        process.env.AFILIADO_TAG                || 'co20251022064125',
  LIMITE_POR_EXECUCAO: parseInt(process.env.LIMITE_POR_EXECUCAO || '166'),
  LOTE_AFILIADO:       parseInt(process.env.LOTE_AFILIADO       || '30'),
  DEDUPE_TTL_HORAS:    parseInt(process.env.DEDUPE_TTL_HORAS    || '24'),
  PAGE_SIZE:           17,
  MAX_PAGES_POR_FONTE: 50,
};

// Filtros globais aplicados a todos os perfis
const FILTROS_GLOBAIS = {
  PRECO_MIN:     20,
  DESCONTO_MIN:  10,
  EXIGE_IMAGEM:  true,
};

// Perfis de coleta — agora orientados por intenção real de compra
const PERFIS = [
  {
    id:   1,
    nome: 'Moda Masculina Barata',
    categorias_extra: ['MLB1430'],
    filtros: { comissao_min: 0, desconto_min: 10 },
  },
  {
    id:   2,
    nome: 'Moda Feminina Barata',
    categorias_extra: ['MLB1430'],
    filtros: { comissao_min: 0, desconto_min: 10 },
  },
  {
    id:   3,
    nome: 'Tênis, Sapatos & Calçados',
    categorias_extra: ['MLB1430'],
    filtros: { comissao_min: 0, desconto_min: 10 },
  },
  {
    id:   4,
    nome: 'iPhone, Celulares & Acessórios',
    categorias_extra: ['MLB1051', 'MLB1000'],
    filtros: { comissao_min: 0, desconto_min: 5 },
  },
  {
    id:   5,
    nome: 'Fitness, Academia & Suplementos',
    categorias_extra: ['MLB1276', 'MLB264586'],
    filtros: { comissao_min: 0, desconto_min: 10 },
  },
  {
    id:   6,
    nome: 'Casa Útil & Organização',
    categorias_extra: ['MLB1574', 'MLB5726'],
    filtros: { comissao_min: 0, desconto_min: 10 },
  },
  {
    id:   7,
    nome: 'Beleza & Cuidados Pessoais',
    categorias_extra: ['MLB1246'],
    filtros: { comissao_min: 0, desconto_min: 10 },
  },
  {
    id:   8,
    nome: 'Ferramentas, Auto & Utilidades',
    categorias_extra: ['MLB263532', 'MLB5672'],
    filtros: { comissao_min: 0, desconto_min: 10 },
  },
  {
    id:   9,
    nome: 'Mix Achadinhos Virais',
    categorias_extra: ['MLB1430', 'MLB1574', 'MLB1246', 'MLB1276', 'MLB1051'],
    filtros: { comissao_min: 0, desconto_min: 10 },
  },
];

// Keywords por perfil — o scraper passa a vasculhar como comprador
const KEYWORDS_POR_PERFIL = {
  1: [
    'camiseta masculina',
    'camiseta masculina barata',
    'camisa polo masculina',
    'calça jeans masculina',
    'bermuda masculina',
    'short masculino',
    'moletom masculino',
    'jaqueta masculina',
    'kit cueca',
    'cueca boxer kit',
    'kit meia masculina',
    'mochila masculina',
    'carteira masculina',
    'boné masculino',
    'chinelo masculino',
  ],

  2: [
    'vestido feminino',
    'blusa feminina',
    'cropped feminino',
    'calça jeans feminina',
    'short feminino',
    'saia feminina',
    'legging feminina',
    'conjunto feminino',
    'bolsa feminina',
    'mochila feminina',
    'sandalia feminina',
    'rasteirinha feminina',
    'kit calcinha',
    'pijama feminino',
    'moda feminina barata',
  ],

  3: [
    'tenis masculino',
    'tenis masculino barato',
    'tenis feminino',
    'tenis feminino barato',
    'tenis corrida masculino',
    'tenis corrida feminino',
    'tenis casual masculino',
    'tenis casual feminino',
    'sapato masculino',
    'sapato social masculino',
    'bota feminina',
    'bota masculina',
    'sandalia feminina',
    'chinelo masculino',
    'chinelo feminino',
  ],

  4: [
    'iphone',
    'iphone 11',
    'iphone 12',
    'iphone 13',
    'iphone 14',
    'iphone 15',
    'celular samsung',
    'celular motorola',
    'celular xiaomi',
    'redmi',
    'poco',
    'capinha iphone',
    'pelicula iphone',
    'carregador iphone',
    'cabo iphone',
    'fone bluetooth',
    'smartwatch',
    'power bank',
  ],

  5: [
    'creatina',
    'whey protein',
    'pré treino',
    'pre treino',
    'coqueteleira',
    'garrafa academia',
    'camiseta dry fit',
    'short academia masculino',
    'legging fitness feminina',
    'top fitness feminino',
    'luva academia',
    'halteres',
    'kit halteres',
    'corda pular',
    'tapete yoga',
    'elastico treino',
    'munhequeira academia',
  ],

  6: [
    'organizador cozinha',
    'organizador geladeira',
    'pote hermetico',
    'kit pote hermetico',
    'tapete banheiro',
    'tapete cozinha',
    'kit banheiro',
    'kit cozinha',
    'escorredor louça',
    'jogo de cama',
    'edredom',
    'toalha banho',
    'panela',
    'kit panela',
    'air fryer',
    'fritadeira air fryer',
    'garrafa térmica',
    'copo térmico',
    'ventilador',
  ],

  7: [
    'perfume',
    'perfume masculino',
    'perfume feminino',
    'desodorante',
    'kit shampoo',
    'shampoo',
    'condicionador',
    'hidratante corporal',
    'protetor solar',
    'kit skincare',
    'maquiagem',
    'base maquiagem',
    'batom',
    'secador cabelo',
    'chapinha',
    'escova secadora',
    'barbeador',
    'máquina de cortar cabelo',
  ],

  8: [
    'parafusadeira',
    'furadeira',
    'kit ferramentas',
    'caixa ferramentas',
    'multimetro',
    'trena',
    'chave de fenda',
    'compressor de ar',
    'calibrador pneu',
    'aspirador carro',
    'capa banco carro',
    'suporte celular carro',
    'camera veicular',
    'organizador porta malas',
    'lavadora alta pressão',
  ],

  9: [
    'achadinhos',
    'oferta relampago',
    'promoção',
    'produto barato',
    'kit cozinha',
    'tenis barato',
    'camiseta barata',
    'sapato barato',
    'capinha iphone',
    'fone bluetooth',
    'garrafa térmica',
    'organizador',
    'tapete banheiro',
    'creatina',
    'perfume',
    'mochila',
    'smartwatch',
  ],
};

module.exports = {
  settings,
  FILTROS_GLOBAIS,
  PERFIS,
  KEYWORDS_POR_PERFIL,
};
